### ISSUE TITLE
[DOCS] issue 및 PR 템플릿 등록, Review Assign 자동화

### ISSUE THREAD

**Issue by Kim-TaeUk** [Team-WSS/WSS-Server#11]
## Description
- Issue와 PR 템플릿을 등록한다.
- PR 생성 시 `assginee`와 `reviewer`를 자동으로 등록한다. 

## To-Do

- [x] Issue 템플릿 등록
- [x] PR 템플릿 등록
- [x] PR 생성 시 `assginee`와 `reviewer` 등록 자동화
