### ISSUE TITLE
[FEAT] 일반 검색 API 구현

### ISSUE THREAD

**Issue by rinarina0429** [Team-WSS/WSS-Server#124]
## Description
일반 검색(상세탐색X) API를 구현합니다.

## To-Do
- [x] 일반 검색 API 구현
- [x] 작품 제목 -> 작가가 검색
- [x] 공백 검색 시 빈값
- [x] 인기순으로 정렬
- [x] resultCount 구현

## Reference
- [Spring Boot에 QueryDSL을 사용해보자](https://tecoble.techcourse.co.kr/post/2021-08-08-basic-querydsl/)
- [A Guide to Querydsl with JPA](https://www.baeldung.com/querydsl-with-jpa-tutorial)
