### ISSUE TITLE
[FIX] 관심있어요와 평가 관련 오류 수정

### ISSUE THREAD

**Issue by rinarina0429** [Team-WSS/WSS-Server#129]
## Description
관심있어요와 평가 관련된 오류를 수정합니다.

## To-Do
- [ ] 관심있어요 등록 -> 작품정보 기본 조회
- [ ] 관심있어요 등록 -> 작품평가 생성
- [ ] 작품평가 생성 -> 관심있어요 등록 -> 작품평가 삭제 -> 작품평가 생성
