### ISSUE TITLE
[FIX] 닉네임 정책 변경으로 인한 요구사항 반영

### ISSUE THREAD

**Issue by ChaeAg** [Team-WSS/WSS-Server#210]
## Description
<img width="316" alt="image" src="https://github.com/user-attachments/assets/d476876e-754d-423f-9cec-894c10d679fb">

위 사진처럼 10/9일자로 유저 닉네임 관련 정책이 변경되어 해당 요구사항을 반영한다.
변경된 사항 : <특수문자 `-`, `_` 사용 가능 -> 특수문자 모두 사용 불가능>, <공백으로 시작, 끝 불가능 -> 공백 아예 포함 불가능>

## To-Do
- [x] 닉네임 특수문자 사용 제한하기
- [x] 닉네임 공백 포함 제한하기
- [x] 관련 예외처리 커스텀
