### ISSUE TITLE
[FEAT] 최소 지원 버전 API 구현

### ISSUE THREAD

**Issue by ChaeAg** [Team-WSS/WSS-Server#233]
## Description
운영체제(OS)에 따라 앱의 최소 지원 버전을 제공하는 API를 구현한다. 
이를 통해 구버전을 사용하는 사용자에게 강제 업데이트를 안내할 수 있도록 한다.

## To-Do
- [x] API 명세서 작성
- [x] 데이터베이스 `minimum_version` 테이블 생성
- [x] 최소 지원 버전 업데이트 API 구현
- [x] 최소 지원 버전 조회 API 구현
